In [2]:
import numpy as np
from sklearn.decomposition import PCA

In [3]:
m = np.random.randint(256, size=(1000,5))

In [4]:
#m=np.array ([[1,0,0],[0,1,0],[2,0,0],[0,10,0],[23,0,0]])

In [5]:
pca = PCA(n_components=3)
pca.fit(m)

PCA(copy=True, iterated_power='auto', n_components=3, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [6]:
pca.components_

array([[ 0.4103411 ,  0.50760231, -0.42961089, -0.23328963, -0.57876637],
       [ 0.2165474 , -0.1079472 , -0.11430299, -0.83524346,  0.48037258],
       [ 0.35139376, -0.7197157 , -0.55189903,  0.22366062, -0.06257087]])

In [7]:
pca.explained_variance_ 

array([ 6228.18746591,  5809.35022777,  5315.81639286])

In [8]:
from scipy import linalg
U,s,Vh = linalg.svd(m)
b1=Vh[0,:]
b2=Vh[1,:]

In [11]:
s

array([ 9335.34692349,  2491.52346965,  2406.15562951,  2298.45655545,
        2191.55473753])

In [13]:
Vh.T[:,0]

array([-0.43988708, -0.4636113 , -0.43298995, -0.44680401, -0.45216125])

In [14]:
b1

array([-0.43988708, -0.4636113 , -0.43298995, -0.44680401, -0.45216125])

In [ ]:
m.dot(pca.components_.T)

In [ ]:
U.shape

In [ ]:
s.resize(5)

In [ ]:
S=np.diag(s)

In [ ]:
U.dot(S)

In [ ]:
s.resize(3)

In [ ]:
s

In [ ]:
A=np.diag(s)

In [ ]:
b=np.zeros((2,3))

In [ ]:
S=np.concatenate((A, b), axis=0)

In [ ]:
U.dot(S)