In [1]:
from FinanceDate import *
import tensorflow as tf
import numpy as np

In [2]:
FinanceDate(datetime.now(),"+1Y")

datetime.datetime(2018, 5, 14, 15, 34, 10, 817422)

In [3]:
ref=np.random.choice(np.arange(10),15,p=[0.5,0.5/9,0.5/9,0.5/9,0.5/9,0.5/9,0.5/9,0.5/9,0.5/9,0.5/9 ])

In [4]:
val=np.random.choice(np.arange(10),15,p=[0.5,0.5/9,0.5/9,0.5/9,0.5/9,0.5/9,0.5/9,0.5/9,0.5/9,0.5/9 ])

In [5]:
ref=ref.astype(np.float32)

In [6]:
val=val.astype(np.float32)

In [7]:
ref_check=(np.abs(ref)>0)#.astype(int)

In [8]:
val_check =(np.abs(val)>0)#.astype(int)

In [9]:
compare=(ref_check==(val_check)).astype(int)

In [10]:
compare.sum()


7

In [11]:
tf.reset_default_graph()
X=tf.placeholder(tf.float32,[None,15])
Y=tf.placeholder(tf.float32,[None,15])
init=tf.global_variables_initializer()

p=tf.shape(X)
#X_check = tf.Variable(tf.zeros(15),name="x_check",dtype=tf.float32) 
p=tf.shape(X)

X_check = ( tf.abs(X)>0)
y_check = tf.abs(Y)>0
compare_check=tf.equal(X_check,(y_check))
compare=tf.reduce_sum(tf.cast((compare_check),tf.int32))

In [12]:
with tf.Session() as sess:
    init.run()
    xx = sess.run(X, feed_dict={X:[ref],Y:[val]})
    s=sess.run(X_check,feed_dict={X:[ref],Y:[val]})
    s2=sess.run(y_check,feed_dict={X:[ref],Y:[val]})
    s3=  sess.run(compare_check,feed_dict={X:[ref],Y:[val]})
    c = sess.run(compare,feed_dict={X:[ref],Y:[val]})

In [13]:
c

7

In [14]:
s==s2

array([[ True, False,  True,  True,  True, False, False, False, False,
        False,  True,  True,  True, False, False]], dtype=bool)

In [15]:
a=[[1,2,3],
   [4,5,6]]

In [16]:
s3

array([[ True, False,  True,  True,  True, False, False, False, False,
        False,  True,  True,  True, False, False]], dtype=bool)

In [17]:
np.stack(a,axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [18]:
a[0][1]

2